//! The compiled subject registry (RFC keyspace-v2 08).
//!
//! Generated by `zenkey-build` from `tcgui-shared/registry/tc.toml`: the
//! `tc` producer's `Subject` enum with typed constructors and a
//! precedence-ordered parser, its `ProcedureId` enum with `@rpc` key
//! builders, and the raw slice (`tc::REGISTRY_TOML`) the backend serves on
//! `@rpc/tc/introspect` (RFC 08 §6).
//!
//! Lints (RFC 08 §5) run at build time — a violating registry file does not
//! compile.

include!(concat!(env!("OUT_DIR"), "/zenkey_registry.rs"));
